/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xue_testalooper_MainActivity */

#ifndef _Included_com_xue_testalooper_MainActivity
#define _Included_com_xue_testalooper_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xue_testalooper_MainActivity
 * Method:    createLooper
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_testalooper_MainActivity_createLooper
  (JNIEnv *, jobject);

/*
 * Class:     com_xue_testalooper_MainActivity
 * Method:    createLooper2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_testalooper_MainActivity_createLooper2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
