/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xue_firstndk_Jni5Test */

#ifndef _Included_com_xue_firstndk_Jni5Test
#define _Included_com_xue_firstndk_Jni5Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xue_firstndk_Jni5Test
 * Method:    createLOCKObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni5Test_createLOCKObject
  (JNIEnv *, jobject);

/*
 * Class:     com_xue_firstndk_Jni5Test
 * Method:    startWatcher
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xue_firstndk_Jni5Test_startWatcher
  (JNIEnv *, jobject);

/*
 * Class:     com_xue_firstndk_Jni5Test
 * Method:    stopWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni5Test_stopWatcher
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_xue_firstndk_Jni5Test
 * Method:    getInteger
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_xue_firstndk_Jni5Test_getInteger
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_xue_firstndk_Jni5Test
 * Method:    setInteger
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni5Test_setInteger
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
