/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xue_firstndk_Jni3Test */

#ifndef _Included_com_xue_firstndk_Jni3Test
#define _Included_com_xue_firstndk_Jni3Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xue_firstndk_Jni3Test
 * Method:    throwEOFExpt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni3Test_throwEOFExpt
  (JNIEnv *, jobject);

/*
 * Class:     com_xue_firstndk_Jni3Test
 * Method:    throwEOFExpt2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni3Test_throwEOFExpt2
  (JNIEnv *, jobject);

/*
 * Class:     com_xue_firstndk_Jni3Test
 * Method:    checkJavaExpt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni3Test_checkJavaExpt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
