/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xue_firstndk_Jni2Test */

#ifndef _Included_com_xue_firstndk_Jni2Test
#define _Included_com_xue_firstndk_Jni2Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xue_firstndk_Jni2Test
 * Method:    raiseSalary
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni2Test_raiseSalary
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xue_firstndk_Jni2Test
 * Method:    printName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni2Test_printName
  (JNIEnv *, jobject);

/*
 * Class:     com_xue_firstndk_Jni2Test
 * Method:    doTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xue_firstndk_Jni2Test_doTask
  (JNIEnv *, jobject);

/*
 * Class:     com_xue_firstndk_Jni2Test
 * Method:    createInstance
 * Signature: ()Lcom/xue/firstndk/Jni2Test;
 */
JNIEXPORT jobject JNICALL Java_com_xue_firstndk_Jni2Test_createInstance
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
